### PR TITLE
fix(circuit): allow timeout option to be false

### LINKED ISSUE #393: Lost ability to disable timeout.
The breaking changes that were released with v4.0 from https://github.com/nodeshift/opossum/pull/366 included the lose of ability to no longer specify `timeout: false`. It's unclear if this was intentional.

My primary use-case for Opossum is to wrap external HTTP calls, in those cases I'd prefer the HTTP client be in control of the timeout instead of Opossum.
So currently, I have to hard code a silly-large number into the option.

The feature was originally added in https://github.com/nodeshift/opossum/pull/202.
The feature was removed from the JSDocs [here](https://github.com/nodeshift/opossum/commit/e4eb8199b21ac62565e2e570bfbdc34f90122119#diff-dbc2c6ba82726efeb035efaaac7c38acL36).

### PR DESCRIPTION
**Pull request by mastermatt**
Allow `false` to be provided for the `timeout` option as a means of disabling the entire feature.

Note that the logic to skip the timeout feature if the option is falsey was still in place was did not need an update for this fix.
https://github.com/nodeshift/opossum/blob/30a83b361fc0e61f111ff846709712e9c476c77d/lib/circuit.js#L495

I'm not sure a good way to test this beyond monkey-patching the global `setTimeout` and asserting it wasn't called. So I haven't added a test, but would be happy to add one if there is a preferred method. 

Fixes #393.

### CODE REVIEW

**Comment by lance** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/circuit.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/nodeshift/opossum/pullRequest?prid=4803959&bid=15984772)

**Comment by lance** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/circuit.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/nodeshift/opossum/pullRequest?prid=4803959&bid=15984772)

**Comment by lance** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/circuit.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/nodeshift/opossum/pullRequest?prid=4803959&bid=15984772)

**Comment by mastermatt** [comment]
@lance test added

**Comment by Ryan-Kalinowski** [comment]
I don't know if this is the correct place to leave this feedback, or if I should open an issue in this repo or DefinitelyTyped, but the typings for the timeout are broken. The only way to disable the timeout functionality is to disable type checking for that field.

**Comment by mastermatt** [comment]
@Ryan-Kalinowski this lib does not bundle it's types.
You're best option is to open a PR here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/opossum

**Pull request merged**
