### PR TITLE
Set entrypoint to dist/opossum.js

### PR DESCRIPTION
**Pull request by tavogel**
With https://github.com/nodeshift/opossum/pull/380 and https://github.com/nodeshift/opossum/releases/tag/v4.2.0, we are now using Babel to transpile our distribution.

However, I was perplexed... I still get the same error as before, where my app is choking on the use of template literals. I realized the problem is because the distribution folder is not used at all by this library. We ship a transpiled and minified dependency, but don't use either of them by default, because the entrypoint is set to the library path. For the moment I can bypass the error by explicitly using the dist path in my app... `require('opossum/dist/opossum')`.

This pull request updates the package to point to the transpiled distribution of Opossum. Additionally, it only ships the `dist` folder, not the `lib`, so the package size is reduced. I confirmed this fixes my issue as well.

### CODE REVIEW

**Comment by tavogel** [comment]
Any news? My workaround for now is: `const CircuitBreaker = require('opossum/dist/opossum');`

**Comment by lance** [comment]
@tavogel apologies - I have been traveling and this just slipped through the cracks. I'll take a look today.

**Comment by lance** [comment]
@tavogel if you would please update the branch, I'll merge. Thanks.

**Comment by tavogel** [comment]
@lance rebased!

**Comment by lholmquist** [comment]
I had to revert this commit since when i did the 4.2.2 release,  opossum broke for people,  https://github.com/nodeshift/opossum/issues/392,  I think we need to revisit this issue

**Pull request merged**
