### PR TITLE
feat: add call() method to CircuitBreaker

### PR DESCRIPTION
**Pull request by lance**
This allows callers to control the `this` context when firing
a circuit breaker function.

Fixes: https://github.com/nodeshift/opossum/issues/349

### CODE REVIEW

**Comment by lance** [comment]
Changed this so that the new circuit method is `call()` instead of `apply()` since semantically it's actually like `Function.prototype.call` instead of `Function.prototype.apply`.

**Comment by lance** [comment]
@lholmquist I used `call()` because it behaves pretty much just like `Function.call()`. And since `Function.call()` is a static function, we aren't overriding anything with this. But I can be persuaded if you can come up with a good name. :)

**Comment by lholmquist** [comment]
I don't have anything in mind,  so call is good :)

**Comment by helio-frota** [comment]
LGTM :+1:

**Pull request merged**
