### PR TITLE
Add Node 15 support

### PR DESCRIPTION
**Pull request by Hongbo-Miao**

### CODE REVIEW

**Comment by Hongbo-Miao** [comment]
Why failed on Node 10 and 12...

**Comment by lholmquist** [comment]
looks like it is failing when trying to publish the coverage report to coveralls

**Comment by helio-frota** [comment]
that seems flakey issue with coveralls.

this is the latest working :

**Comment by helio-frota** [comment]
@Hongbo-Miao @lholmquist  this may be config, I can take a look on that later https://github.com/nodeshift/opossum/pull/474

**Comment by richardlau** [comment]
> 
> 
> @Hongbo-Miao @lholmquist this may be config, I can take a look on that later #474

@helio-frota The failure is going to be because the PR came from a fork and those can't access secrets (being used to provide the token for coverage). We may be able to change the workflow to use the `pull_request_target` instead of `pull_request` event, see https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks.

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
I've rebased this after landing https://github.com/nodeshift/opossum/pull/476 on master and we now have a passing CI 🎉.

**Review by lholmquist — APPROVED** [review]
Thanks, @Hongbo-Miao

**Comment by Hongbo-Miao** [comment]
You are welcome : )

**Comment by ale-grosselle** [comment]
@Hongbo-Miao Could you release this implementation in a version please?

**Pull request merged**
